import '../css/style.css'
import '/src/counter.js'
import '/src/news.js'
import '/src/mail.js'

import '../resourses/images/1.JPG'
import '../resourses/images/2.JPG'
import '../resourses/images/3.JPG'
import '../resourses/images/4.JPG'
import '../resourses/images/5.JPG'
import '../resourses/images/exhibition.jpeg'
import '../resourses/images/group.JPG'
import '../resourses/images/pictures.jpeg'
import '../resourses/images/ship.jpg'
import '../resourses/images/trees.jpeg'
import '../resourses/images/ushacov.jpeg'

import '../resourses/icons/eye.png'
import '../resourses/icons/to_left.png'
import '../resourses/icons/to_right.png'
import '../resourses/icons/university.png'
